# Generated by Django 2.2.3 on 2019-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_entry', '0003_auto_20191103_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
