# Generated by Django 2.2.3 on 2019-11-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_entry', '0004_auto_20191103_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_entry.Product'),
        ),
    ]
