# Generated by Django 2.2.3 on 2019-11-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_entry', '0006_auto_20191104_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_num',
        ),
    ]
