# Generated by Django 2.2.3 on 2019-11-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_entry', '0007_remove_document_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Anzahl'),
        ),
    ]
