# Generated by Django 2.2.3 on 2019-11-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_entry', '0008_auto_20191107_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
